### ISSUE TITLE
No UTF-8 support

### ISSUE THREAD

**Issue by progxaker** [la-ninpre/tg2md#1]
> cat example.json
```json
{
 "type": "saved_messages",
 "id": 123456,
 "messages": [
  {
   "id": 1,
   "type": "message",
   "date": "1990-01-01T00:00:00",
   "from": "Test",
   "from_id": 123456,
   "forwarded_from": "ForTest",
   "saved_from": "ForTest",
   "text": [
    {
     "type": "bold",
     "text": "Teler"
    },
    " - терминальная система обнаружения вторжений и оповещения об угрозах в режиме реального времени, основанная на мониторинге веб-журналов\n\nПоддерживает большой набор web-логов:\n\n- Apache\n- Nginx\n- Nginx Ingress\n- Amazon S3\n- Elastic LB\n- CloudFront\n\nИспользовать можно готовые бинарные файлы или установочный скрипт или docker контейнер:\n\n",
    {
     "type": "link",
     "text": "https://github.com/kitabisa/teler#demo"
    }
   ]
  }
 ]
}
```

> start.py example.json
```python
Traceback (most recent call last):
  File "D:\Temp\29\start.py", line 255, in <module>
    main()
  File "D:\Temp\29\start.py", line 232, in main
    data = json.load(f)
  File "C:\Program Files\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\Python39\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 728: character maps to <undefined>
```

**Comment by progxaker** [comment]
I suggest the following changes:
```diff
parser.add_argument(
            'json', metavar='json_file',
-           type=open,
            help='result.json file from telegram export')

...

- with args.json as f:
+ with open(args.json, 'r', encoding='utf-8') as f:

...

- with open(post_path, 'w') as f:
+ with open(post_path, 'w', encoding='utf-8') as f:
```

**Comment by la-ninpre** [comment]
Oh, thanks. I'll check that. I think you can make a pull request?

**Comment by progxaker** [comment]
Ok, I was [make](https://github.com/la-ninpre/tg2md/pull/2/commits/59ad206e53b9eb9f57d2fa445f7920c1900d0575) the pull request.

**Comment by la-ninpre** [comment]
I merged the changes and added cyrillic string to test it. For me it's working. Was the problem fixed for you?

**Comment by progxaker** [comment]
Yes, this solved my problem. Thanks

**Comment by la-ninpre** [comment]
So well. Glad you've find a use for this thing :)
